/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * Order Status
 */
export enum Status {
    Placed = "placed",
    Approved = "approved",
    Delivered = "delivered",
}

export class Order extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "complete" })
    complete?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "petId" })
    petId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "shipDate" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    shipDate?: Date;

    /**
     * Order Status
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: Status;
}
