/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class PetPetIdBody extends SpeakeasyBase {
    /**
     * Updated name of the pet
     */
    @SpeakeasyMetadata({ data: "form, name=name" })
    name?: string;

    /**
     * Updated status of the pet
     */
    @SpeakeasyMetadata({ data: "form, name=status" })
    status?: string;
}
