/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class FindPetsByStatusSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    petstoreAuth: string;
}

export class FindPetsByStatusRequest extends SpeakeasyBase {
    /**
     * Status values that need to be considered for filter
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=status" })
    status: string;
}

export class FindPetsByStatusResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * successful operation
     */
    @SpeakeasyMetadata()
    findPetsByStatus200ApplicationJSONString?: string;

    /**
     * successful operation
     */
    @SpeakeasyMetadata()
    findPetsByStatus200ApplicationXMLString?: string;
}
