/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class FindPetsByStatusRequest extends SpeakeasyBase {
    /**
     * Status values that need to be considered for filter
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=status" })
    status: string;
}

export class FindPetsByStatusResponse extends SpeakeasyBase {
    /**
     * successful operation
     */
    @SpeakeasyMetadata()
    twoHundredApplicationJsonRes?: string;

    /**
     * successful operation
     */
    @SpeakeasyMetadata()
    twoHundredApplicationXmlRes?: string;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
