/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./addpetjson";
export * from "./addpetraw";
export * from "./createuser";
export * from "./createuserswitharrayinput";
export * from "./createuserswithlistinput";
export * from "./deleteorder";
export * from "./deletepet";
export * from "./deleteuser";
export * from "./findpetsbystatus";
export * from "./findpetsbytags";
export * from "./getinventory";
export * from "./getorderbyid";
export * from "./getpetbyid";
export * from "./getuserbyname";
export * from "./loginuser";
export * from "./logoutuser";
export * from "./placeorder";
export * from "./updatepetjson";
export * from "./updatepetraw";
export * from "./updatepetwithform";
export * from "./updateuser";
export * from "./uploadfile";
